### ISSUE TITLE
On a default Ubuntu one-node installation, pods fail due too many open files

### ISSUE THREAD

**Issue by andreaskaris** [opennetworkinglab/aether-amp#1] opened 2023-08-25 14:37 UTC
On a default Ubuntu one-node installation, pods fail due too many open files

https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files has a solution for this:
```
fs.inotify.max_user_watches=524288
fs.inotify.max_user_instances=512
```

**Comment by llpeterson** [comment] 2023-08-25 16:16
I haven't seen that issue. Is it due to an unreasonably low setting of max_*, or is it symptomatic of AMP going off the rails? What was your environment? (I'm guessing it worked ok once you made the change, but it would be good to know the root cause.)

**Comment by andreaskaris** [comment] 2023-08-25 19:08
Let me reproduce it again some time next week and share some more logs :-) sorry for the sparse initial report

**Comment by gab-arrobo** [comment] 2024-04-17 16:21
@llpeterson it looks like this got fixed by you in this [commit](https://github.com/opennetworkinglab/aether-k8s/commit/638d14a83c6d44b871330f60068375869d82612d)

**Closed** 2024-05-15 19:19 UTC
